config/routes.rb
Homtanks::Application.routes.draw do
  root 'dashboard#show'

  get 'reload' => 'dashboard#reload'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_filter :config_api
  
  def show
    @star = Tmdb::Person.popular[rand(0..19)]
  end
  
  def reload
    redirect_to :back
  end
  
  protected
  
  def config_api
    Tmdb::Api.key("8b893016b1b81c808208f53339ef5d99")
    Tmdb::Api.language("de")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
  def change_name star_name
    array = star_name.split
    first_char = array[0][0]
    last_char = array[-1][0]
    
    array[0][0] = last_char
    array[-1][0] = first_char
    
    array.join(' ')
  end
end

app/views/dashboard/show.haml
.wrapper
  %h1
    = change_name(@star.name)
  - if @star.profile_path.present?
    %img{ :src => "http://cf2.imgobject.com/t/p/w500" + @star.profile_path, :width => "200" }
  - else
    %img{ :src => "http://www.hollandlift.com/wp-content/themes/hollandlift/assets/images/no_image.jpg", :width => "200" }
  %h5= 'Orginal Name: ' + @star.name
  %hr
  %h3 Bekannt aus: 
  - @star.known_for.each do |movie|
    %p= movie.title
  
  = button_to "Refresh page", reload_path, :method => :get

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Homtanks</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>